CREATE TABLE users (
  id TEXT PRIMARY KEY UNIQUE NOT NULL,
  login VARCHAR(16) NOT NULL UNIQUE,
  password VARCHAR(255) DEFAULT NULL,
  name VARCHAR(20) NOT NULL,
  surname VARCHAR(60) DEFAULT NULL
);
